apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-fastapi-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-fastapi-web-app
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/guyzsarun/python-fastapi-accelerator
      ref:
        branch: main
